// Load Environment variables
require('dotenv').load();

// paystack module is required to make charge token call
var paystack = require('paystack')(process.env.PAYSTACK_SECRET_KEY);

// uuid module is required to create a random reference number
var uuid     = require('node-uuid');

var express =  require('express');
var app = require('express')();
var bodyParser = require('body-parser');

app.set('port', (process.env.PORT || 5000));
app.use(express.static(__dirname + '/public'));

app.use(bodyParser.json());       // to support JSON-encoded bodies
app.use(bodyParser.urlencoded({   // to support URL-encoded bodies
  extended: true
}));

app.get('/', function(req, res) {
  res.send('<body><head><link href="favicon.ico" rel="shortcut icon" /></head><body><h1>Awesome!</h1><p>Your server is set up. Go ahead and configure your Paystack sample apps to post <b>[email, token, amountinkobo]</b> to <a href="#">https://'+req.headers.host+'/charge/</a>.</p></body></html>');
});

app.post('/charge', function(req, res) {
    var token        = req.body.token,
        email        = req.body.email,
        amountinkobo = req.body.amountinkobo;
        
        
    paystack.transaction.chargeToken({
      token:     token,        // token sent by mobile app, to be generated by mobile app
      email:     email,        // a valid email address
      amount:    amountinkobo, // only kobo and must be integer
      reference: uuid.v1()     // time-based uuid
    },function(error, body) {
       res.send({error:error, body:body});
    });
});

//The 404 Route (ALWAYS Keep this as the last route)
app.get('/*', function(req, res){
  res.status(404).send('Only a post to /charge is allowed');
});

app.listen(app.get('port'), function() {
  console.log("Node app is running at localhost:" + app.get('port'))
})
